[package]
name = "toy_kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "toy_kernel"
test = false
bench = false


[dependencies]
bootloader = "0.9"
volatile = "0.2.6"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
